GET http://localhost:5000/api/protected
Authorization: Bearer 
### 
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "Alex"
}

###
POST http://localhost:5000/auth/token
Content-Type: application/json

{
    "token": ""
}

###
DELETE http://localhost:5000/auth/logout
Content-Type: application/json

{
    "token": ""
}